# Fase SEMMA — Sample (Amostragem)

## Definição do Problema de Negócio
O objetivo deste projeto é prever o risco de inadimplência de clientes, identificando a probabilidade de um indivíduo apresentar atraso significativo no pagamento de suas obrigações financeiras. Esse tipo de problema é comum em cenários de **credit scoring**, onde instituições financeiras precisam tomar decisões mais seguras na concessão de crédito.

## Fontes de Dados
Os dados utilizados neste projeto são provenientes do dataset **Give Me Some Credit**, amplamente utilizado para problemas de risco de crédito.

- Tipo de fonte: arquivo estruturado (CSV)
- Origem: base pública para modelagem de crédito
- Conteúdo: informações financeiras e comportamentais dos clientes

## Extração dos Dados
Os dados são carregados diretamente a partir de arquivos locais no ambiente do notebook Jupyter.

Principais etapas:
- Leitura do arquivo CSV
- Verificação inicial da estrutura dos dados
- Inspeção de colunas e tipos de dados

### Dados Treino

In [12]:
import pandas as pd
df_train = pd.read_csv("../data/raw/cs-training.csv")
df_train = df_train.drop(columns=["Unnamed: 0"]) # Extração de variavel indice
df_train.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [13]:
df_train.dtypes

SeriousDlqin2yrs                          int64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
dtype: object

### Dados Teste

In [14]:
df_test = pd.read_csv("../data/raw/cs-test.csv")
df_test = df_test.drop(columns=["Unnamed: 0"]) # Extração de variavel indice
df_test.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,NaN,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0
1,NaN,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0
2,NaN,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0
3,NaN,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0
4,NaN,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0

In [15]:
df_test.dtypes

SeriousDlqin2yrs                        float64
RevolvingUtilizationOfUnsecuredLines    float64
age                                       int64
NumberOfTime30-59DaysPastDueNotWorse      int64
DebtRatio                               float64
MonthlyIncome                           float64
NumberOfOpenCreditLinesAndLoans           int64
NumberOfTimes90DaysLate                   int64
NumberRealEstateLoansOrLines              int64
NumberOfTime60-89DaysPastDueNotWorse      int64
NumberOfDependents                      float64
dtype: object

### Conclusão
Ambas as bases são bastante consistente entre si, sendo todas om os mesmos tipos de dados por coluna e ja trazer os dados de teste sem a variavel target.

## Variável Alvo (Target)
A variável alvo do modelo é:
- **SeriousDlqin2yrs**  
  - Valor **1**: cliente apresentou atraso superior a 90 dias (inadimplente)  
  - Valor **0**: cliente não apresentou atraso relevante


## Export de dados Dados

In [17]:
df_train.to_csv("../data/processed/train_data.csv",index=False)
df_test.to_csv("../data/processed/test_data.csv",index=False)